datasets:
  taiwan_captions: # name of the dataset builder
    dataset_card: dataset_card/taiwan_caption.md
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: "C:\\Users\\Chunill\\Program\\NSTC\\code\\get_photo\\train.json"
          storage: "C:\\Users\\Chunill\\Program\\NSTC\\code\\get_photo\\train.json"
        val:
          url: "C:\\Users\\Chunill\\Program\\NSTC\\code\\get_photo\\val.json"
          storage: "C:\\Users\\Chunill\\Program\\NSTC\\code\\get_photo\\val.json"
        test:
          url: "C:\\Users\\Chunill\\Program\\NSTC\\code\\get_photo\\test.json"
          storage: "C:\\Users\\Chunill\\Program\\NSTC\\code\\get_photo\\test.json"
      images:
        storage: "C:\\Users\\Chunill\\Program\\NSTC\\code\\get_photo\\image"