datasets:
  taiwan_captions: # name of the dataset builder
    dataset_card: dataset_card/taiwan_caption.md
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: "taiwan_caption_data\\train.json"
          storage: "taiwan_caption_data\\train.json"
        val:
          url: "taiwan_caption_data\\val.json"
          storage: "taiwan_caption_data\\val.json"
        test:
          url: "taiwan_caption_data\\test.json"
          storage: "taiwan_caption_data\\test.json"
      images:
        storage: "taiwan_caption_data\\image"